name: Build and Release Ansible EE

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
jobs:
  build-and-publish:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version:
          - 3.8
    env:
      IMAGE_NAME: openshift-demos-ansible-ee
      IMAGE_TAGS: latest
    steps:
      - name: Checkout
        id: git_checkout
        uses: actions/checkout@v2

      - uses: GoogleCloudPlatform/release-please-action@v2.24.1
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          bump-minor-pre-major: true

      - name: Setup python
        uses: actions/setup-python@v2
        if: ${{ steps.release.outputs.release_created }}
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Packages
        run: |
          pip install poetry && poetry install

      - name: Login to Quay.io
        uses: docker/login-action@v1
        if: ${{ steps.release.outputs.release_created }}
        with:
          registry: quay.io
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_TOKEN }}
          logout: true

      - name: Build the Ansible EE Image
        id: build-image
        if: ${{ steps.release.outputs.release_created }}
        run: |
          poetry run ansible-builder build --tag $IMAGE_TAG
          podman push $IMAGE_TAG
          podman tag $IMAGE_TAG $IMAGE_LATEST
          podman push $IMAGE_LATEST
        env:
          IMAGE_TAG: "${{ secrets.QUAYIO_REPO }}/${{ env.IMAGE_NAME }}:${{ steps.release.outputs.tag_name }}"
          IMAGE_LATEST: "${{ secrets.QUAYIO_REPO }}/${{ env.IMAGE_NAME }}:latest"
