name: Build and Release Ansible EE

on:
  push:
    branches:
      - "master"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: openshift-demos-ansible-ee
      IMAGE_TAGS: latest
    steps:
      - name: Checkout
        id: git_checkout
        uses: actions/checkout@v2
      # TODO add step for ansible builder ee

      # - uses: GoogleCloudPlatform/release-please-action@v2.24.1
      #   id: release
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     release-type: simple
      #     bump-minor-pre-major: true

      - uses: actions/setup-python@v1
        #if: ${{ release.release_created }}
      - uses: BSFishy/pip-action@v1
        #if: ${{ release.release_created }}
        with:
          packages: |
            ansible-builder

      - name: Login to Quay.io
        uses: redhat-actions/podman-login
        #if: ${{ release.release_created }}
        with:
          registry: quay.io
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_TOKEN }}
          logout: true

      - name: Build the Ansible EE Image
        id: build-image
        #if: ${{ release.release_created }}
        run: |
          ansible-builder build --tag ${{ env.IMAGE_NAME }}:latest
          podman push ${{ env.IMAGE_NAME }}:latest
